#!/usr/bin/env bash

if ! command -v mvn 2>&1 >/dev/null
then
	echo "Maven is not on \$PATH. Please install Maven, then run this script again."
	exit 1
fi

if ! command -v npx 2>&1 >/dev/null
then
	echo "NPX, and likely Node, is not on \$PATH. Install Node.js, then run this script again."
	exit 1
fi

if ! command -v java 2>&1 >/dev/null
then
	echo "Java is not on \$PATH. Install Java, then run this script again."
	exit 1
fi

if ! [ -x ./clean ]
then
    echo "./clean is not executable. Please chmod +x ./clean, then re-run this script."
    exit 1
fi

./clean
echo "Initializing database"
mvn install exec:exec
echo "Initializing web frontend"

npx yarn --cwd web/ build

echo "Startup"
mvn spring-boot:run
