on:
  push:
    paths:
      - "**.java"
      - ".github/workflows/javadoc.yml"

jobs:
  generate_javadoc:
    runs-on: ubuntu-24.04
    steps:
      - name: Set-up Java and Maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-distribution: "adopt-hotspot"
          maven-version: '3.9.6'
          java-version: '21'

      - name: Generate JavaDoc
        run: mvn -q verify javadoc:javadoc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: 'javadoc'
          publish_dir: 'target/reports/apidocs'
          external_repository: 'shrapnelnet/CI553-CW-2-Javadoc'
          personal_token: ${{ secrets.PERSONAL_TOKEN }}