on:
  push:
    branches:
      - master

jobs:
  generate_swagger:
    runs-on: ubuntu-latest
    steps:
      - name: Set-up Java and Maven
      - uses: s4u/setup-maven-action@v1.18.0
        with:
          java-distribution: "adopt-hotspot"
          maven-version: '3.9.6'
          java-version: '21'

      - name: Generate OpenAPI spec
        run: mvn -q clean verify