on:
  push:
    paths:
      - "src/main/java/com/shr4pnel/web"
      - "src/main/java/com/shr4pnel/schemas"
    branches:
      - master

jobs:
  generate_swagger:
    runs-on: ubuntu-latest
    steps:
      - name: Set-up Java and Maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-distribution: "adopt-hotspot"
          maven-version: '3.9.6'
          java-version: '21'

      - name: Generate OpenAPI spec
        run: mvn -q clean verify

      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1.3.0
        with:
          output: swagger-ui
          spec-file: target/openapi.json
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui